services:
  kudab-parser-scheduler:
    image: kudab-parser:latest
    user: "${UID}:${GID}"
    build: ./services/kudab-parser
    environment:
      APP_ENV: local
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redispass}
      REDIS_CLIENT: phpredis
    volumes:
      - ./services/kudab-parser:/var/www/html:rw
      - ./services/kudab-parser/vendor:/var/www/html/vendor
      - ./services/kudab-parser/storage:/var/www/html/storage
    working_dir: /var/www/html
    command: php artisan schedule:work
    depends_on:
      redis:
        condition: service_healthy
      kudab-db:
        condition: service_healthy
    restart: unless-stopped

  kudab-api-scheduler:
    image: kudab-api:latest
    user: "${UID}:${GID}"
    build: ./services/kudab-api
    environment:
      APP_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redispass}
    volumes:
      - ./services/kudab-api:/var/www/html:rw
      - ./services/kudab-api/vendor:/var/www/html/vendor
      - ./services/kudab-api/storage:/var/www/html/storage
    working_dir: /var/www/html
    command: php artisan schedule:work
    depends_on:
      redis:
        condition: service_healthy
      kudab-db:
        condition: service_healthy
    restart: unless-stopped

  kudab-api:
    image: kudab-api:latest
    user: "${UID}:${GID}"
    build: ./services/kudab-api
    container_name: ${KUDAB_API_CONTAINER:-kudab-api}
    env_file: .env
    volumes:
      - ./services/kudab-api:/var/www/html:rw
      - ./services/kudab-api/vendor:/var/www/html/vendor
      - ./services/kudab-api/storage:/var/www/html/storage
    expose:
      - "9000"   # php-fpm порт для nginx, НЕ наружу
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost/api/ping || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      kudab-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  kudab-parser:
    environment:
      APP_ENV: local
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redispass}
      REDIS_CLIENT: phpredis
    image: kudab-parser:latest
    user: "${UID}:${GID}"
    build: ./services/kudab-parser
    container_name: ${KUDAB_PARSER_CONTAINER:-kudab-parser}
    env_file: .env
    volumes:
      - ./services/kudab-parser:/var/www/html:rw
      - ./services/kudab-parser/vendor:/var/www/html/vendor
      - ./services/kudab-parser/storage:/var/www/html/storage
    depends_on:
      - kudab-db
      - redis

  kudab-parser-fpm:
    image: kudab-parser:latest
    container_name: kudab-parser-fpm
    env_file: .env
    user: "${UID}:${GID}"
    command: php-fpm
    expose:
      - "9000"
    volumes:
      - ./services/kudab-parser:/var/www/html:rw
      - ./services/kudab-parser/vendor:/var/www/html/vendor
      - ./services/kudab-parser/storage:/var/www/html/storage
    depends_on:
      - kudab-db
      - redis

  kudab-horizon:
    image: kudab-parser:latest
    container_name: ${KUDAB_HORIZON_CONTAINER:-kudab-horizon}
    user: "${UID}:${GID}"
    volumes:
      - ./services/kudab-parser:/var/www/html:rw
    environment:
      APP_ENV: local
      QUEUE_CONNECTION: redis
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redispass}
    command: sh -lc "php artisan optimize:clear && php artisan horizon"
    healthcheck:
      test: [ "CMD-SHELL", "php artisan horizon:status | grep -q 'Horizon is running'" ]
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
      kudab-db:
        condition: service_healthy
    restart: unless-stopped

  kudab-frontend:
    image: kudab-frontend:latest
    build: ./services/kudab-frontend
    container_name: ${KUDAB_FRONTEND_CONTAINER:-kudab-frontend}
    env_file: .env
    expose:
      - "${FRONTEND_PORT:-3000}"
#    volumes:
#      - ./services/kudab-frontend:/app:rw
    depends_on:
      - kudab-api
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3

#  kudab-admin:
#    image: kudab-admin:latest
#    build: ./services/kudab-admin
#    container_name: ${KUDAB_ADMIN_CONTAINER:-kudab-admin}
#    env_file: .env
#    expose:
#      - "${ADMIN_PORT:-8080}"
#    volumes:
#      - ./services/kudab-admin:/app:rw
#    depends_on:
#      - kudab-api

  kudab-bot:
    build:
      context: ./services/kudab-bot
      dockerfile: Dockerfile
      args:
        RUNNER: gunicorn
    image: kudab-bot:latest
    environment:
      BOT_ENV: ${BOT_ENV:-production}
      RUNNER: gunicorn
    depends_on:
      - kudab-db
      - redis
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: unless-stopped

#  kudab-publisher:
#    image: kudab-publisher:latest
#    build: ./services/kudab-publisher
#    container_name: ${KUDAB_PUBLISHER_CONTAINER:-kudab-publisher}
#    env_file: .env
#    volumes:
#      - ./services/kudab-publisher:/app:rw
#    depends_on:
#      - kudab-api

  kudab-nginx:
    image: kudab-nginx:latest
    build: ./services/kudab-nginx
    container_name: ${KUDAB_NGINX_CONTAINER:-kudab-nginx}
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./services/kudab-api/public:/var/www/html/public:ro
      - ./services/kudab-api:/var/www/html:ro
      - ./services/kudab-parser/public:/var/www/parser/public:ro
      - ./services/kudab-parser:/var/www/parser:ro
      - ./certs/prod:/etc/nginx/certs:ro
    depends_on:
      - kudab-api
      - kudab-frontend
      - kudab-bot
#      - kudab-admin
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ && curl -f http://localhost/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    command: [ "redis-server","--appendonly","yes","--requirepass","${REDIS_PASSWORD}" ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "sh", "-lc", "redis-cli -a $REDIS_PASSWORD ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10

  swagger:
    image: swaggerapi/swagger-ui
    container_name: kudab-swagger
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
    volumes:
      - ./docs/swagger:/swagger:ro
    ports:
      - "8181:8080"   # наружу только в dev

  kudab-db:
    image: postgis/postgis:15-3.4
    container_name: ${KUDAB_DB_CONTAINER:-kudab-db}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kudab}
      POSTGRES_USER: ${POSTGRES_USER:-kudab}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kudab}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kudab" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
  redis-data:
